#!/usr/bin/env python3
"""Generate firmware/boot_logo.h from assets/litehawk-logo.png.

The boot splash samples the logo at arbitrary scale/position, so we store
it once at 192x192 as packed 4-bit grayscale (2 px/byte, 18 KB in flash).
Source art is dark strokes on white; we store *ink* intensity (0 = blank,
15 = full stroke) so the firmware can tint it onto a dark background.

Usage: python3 scripts/gen_boot_logo.py
"""

from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
SRC = ROOT / "assets" / "litehawk-logo.png"
DST = ROOT / "firmware" / "boot_logo.h"
SIZE = 192

# Composite onto white first — the source PNG has a transparent background
rgba = Image.open(SRC).convert("RGBA")
white = Image.new("RGBA", rgba.size, (255, 255, 255, 255))
img = Image.alpha_composite(white, rgba).convert("L")

# Trim the uniform white margin so the mark fills the frame
bbox = Image.eval(img, lambda p: 255 - p).getbbox()
img = img.crop(bbox)

# Fit into a square canvas with a small breathing margin
side = max(img.size)
canvas = Image.new("L", (side, side), 255)
canvas.paste(img, ((side - img.width) // 2, (side - img.height) // 2))
margin = side // 16
canvas = canvas.resize((SIZE - 2 * margin,) * 2, Image.LANCZOS)
out = Image.new("L", (SIZE, SIZE), 255)
out.paste(canvas, (margin, margin))

# White (255) -> ink 0; darkest stroke -> ink 15 (normalized so the
# mark hits full brightness even though the source art is dark gray)
pixels = out.load()
darkest = min(pixels[x, y] for y in range(SIZE) for x in range(SIZE))
span = max(1, 255 - darkest)
nibbles = []
for y in range(SIZE):
    for x in range(SIZE):
        nibbles.append(min(15, (255 - pixels[x, y]) * 15 // span))

packed = bytes(
    (nibbles[i] << 4) | nibbles[i + 1] for i in range(0, len(nibbles), 2)
)

lines = [
    "// Auto-generated by scripts/gen_boot_logo.py — do not edit.",
    "// LiteHawk Labs mark, %dx%d, packed 4-bit ink intensity (2 px/byte)." % (SIZE, SIZE),
    "#pragma once",
    "#include <Arduino.h>",
    "",
    "#define BOOT_LOGO_SIZE %d" % SIZE,
    "",
    "const uint8_t BOOT_LOGO[%d] PROGMEM = {" % len(packed),
]
for i in range(0, len(packed), 24):
    chunk = ",".join("0x%02x" % b for b in packed[i : i + 24])
    lines.append("    " + chunk + ",")
lines.append("};")
DST.write_text("\n".join(lines) + "\n")
print(f"wrote {DST} ({len(packed)} bytes)")
